apiVersion: apps/v1
kind: Deployment
metadata:
  name: iamserver-devops-test  
  labels:
    app: iamserver-devops-test
spec:
 # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 3
  selector:
  # This must match the labels we set on the pod!
     matchLabels:
       app: iamserver-devops-test 
       
    # 2. How do want to update the pods?
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  
   # This template field is a regular pod configuration 
  # nested inside the deployment spec
  
  template:
    metadata:
    
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: iamserver-devops-test 
    spec:
      containers:
        - name: iamserver-devops-test
          image: 
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: iamserver-devops-test  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: devops-test
